// <auto-generated />
using System;
using Aveneo_zadanie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aveneo_zadanie.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220320112753_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Aveneo_zadanie.Models.EcbModel", b =>
                {
                    b.Property<string>("currency1")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<string>("currency2")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<DateTime>("dataDate")
                        .HasColumnType("DATE");

                    b.Property<double>("exchangeRate")
                        .HasColumnType("REAL");

                    b.HasKey("currency1", "currency2", "dataDate");

                    b.ToTable("ExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
