// <auto-generated />
using System;
using Aveneo_zadanie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aveneo_zadanie.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Aveneo_zadanie.Models.ApiKey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("key")
                        .HasColumnType("VARCHAR(32)");

                    b.HasKey("id");

                    b.ToTable("GeneratedKeys");
                });

            modelBuilder.Entity("Aveneo_zadanie.Models.EcbModel", b =>
                {
                    b.Property<string>("currency1")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<string>("currency2")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<DateTime>("dataDate")
                        .HasColumnType("DATE");

                    b.Property<double>("exchangeRate")
                        .HasColumnType("REAL");

                    b.HasKey("currency1", "currency2", "dataDate");

                    b.ToTable("ExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
